# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CommitlintGo < Formula
  desc ""
  homepage "https://github.com/jurienhamaker/homebrew-commitlint-go"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jurienhamaker/commitlint/releases/download/v1.0.0/commitlint_Darwin_x86_64.tar.gz"
      sha256 "cea00623f8c635d03deed7dc8a1220b7489a64f478352ffbf27ca1ec996a2513"

      def install
        bin.install "commitlint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jurienhamaker/commitlint/releases/download/v1.0.0/commitlint_Darwin_arm64.tar.gz"
      sha256 "f5cd4ab3f5708f3e49e824ccb436678e8a02d7e47fa189a5ded079d4d4e4dae6"

      def install
        bin.install "commitlint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jurienhamaker/commitlint/releases/download/v1.0.0/commitlint_Linux_x86_64.tar.gz"
      sha256 "f85ad2279f0ea42e1ab38edc1371892a501cfdb39a4e348e5a017681cdc48c44"
      def install
        bin.install "commitlint"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jurienhamaker/commitlint/releases/download/v1.0.0/commitlint_Linux_arm64.tar.gz"
      sha256 "1500de8483bd3a07d7b5684293e686d28dc20769f5bd679de44c3c0e1261d45c"
      def install
        bin.install "commitlint"
      end
    end
  end
end
