# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CommitlintGo < Formula
  desc ""
  homepage "https://github.com/jurienhamaker/homebrew-commitlint-go"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jurienhamaker/commitlint/releases/download/v1.0.0/commitlint_Darwin_x86_64.tar.gz"
      sha256 "fff5215ba0eba370c4ada577f6935878aa050c3c05cfb93bf56e12765e57bc99"

      def install
        bin.install "commitlint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jurienhamaker/commitlint/releases/download/v1.0.0/commitlint_Darwin_arm64.tar.gz"
      sha256 "cd9c0cbcaf57b2ebe67e4293841595d232b967a8cd54d3975aa2a1af85187572"

      def install
        bin.install "commitlint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jurienhamaker/commitlint/releases/download/v1.0.0/commitlint_Linux_x86_64.tar.gz"
      sha256 "5ee5c66ba2a847cde74dc6c4166dd037caf39289db0dc76961e099880735a610"
      def install
        bin.install "commitlint"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jurienhamaker/commitlint/releases/download/v1.0.0/commitlint_Linux_arm64.tar.gz"
      sha256 "bffae4864b7808e25c7ba7643c7310cda918b4c02b7c286ccf95217a8cce8839"
      def install
        bin.install "commitlint"
      end
    end
  end
end
