# This file was generated by GoReleaser. DO NOT EDIT.
cask "commitlint-go" do
  desc "A lightweight, fast, and cross-platform CLI tool for linting Git commit messages."
  homepage "https://github.com/jurienhamaker/homebrew-commitlint-go"
  version "1.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "commitlint"

  on_macos do
    on_intel do
      url "https://github.com/jurienhamaker/commitlint/releases/download/v1.5.0/commitlint_Darwin_x86_64.tar.gz"
      sha256 "3c3b41b13df856a86ada4ac84e36a469878e18a8f2922094727e97118cbeb42e"
    end
    on_arm do
      url "https://github.com/jurienhamaker/commitlint/releases/download/v1.5.0/commitlint_Darwin_arm64.tar.gz"
      sha256 "0729e0baf1a3544791c03267aecc06cdef60ee2469fcf96e9d8edf0fda664309"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jurienhamaker/commitlint/releases/download/v1.5.0/commitlint_Linux_x86_64.tar.gz"
      sha256 "03ed2775507462adaa80d15c2416dc184d59b274fd177037c52ef655638a80dd"
    end
    on_arm do
      url "https://github.com/jurienhamaker/commitlint/releases/download/v1.5.0/commitlint_Linux_arm64.tar.gz"
      sha256 "a4bfb2c60bc96a06c87e271678d45c49c58ca42d4244b1edde16bb38522a07a0"
    end
  end

  # No zap stanza required
end
