# This file was generated by GoReleaser. DO NOT EDIT.
cask "commitlint-go" do
  desc "A lightweight, fast, and cross-platform CLI tool for linting Git commit messages."
  homepage "https://github.com/jurienhamaker/homebrew-commitlint-go"
  version "1.6.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "commitlint"

  on_macos do
    on_intel do
      url "https://github.com/jurienhamaker/commitlint/releases/download/v1.6.0/commitlint_Darwin_x86_64.tar.gz"
      sha256 "466d72e1cb01c783dae69b749db774ab1926d5e552fe3d58dc81e1c5fbe004ee"
    end
    on_arm do
      url "https://github.com/jurienhamaker/commitlint/releases/download/v1.6.0/commitlint_Darwin_arm64.tar.gz"
      sha256 "b19ccdf6e1efa3e9963e1dae332e5f69ac687ea7889e74a35a7a1c14c421e360"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jurienhamaker/commitlint/releases/download/v1.6.0/commitlint_Linux_x86_64.tar.gz"
      sha256 "fd0561a3c20da53d1a152f8c14d2e6e5f762a146c5ba58f0b13e33f00ec6d4ef"
    end
    on_arm do
      url "https://github.com/jurienhamaker/commitlint/releases/download/v1.6.0/commitlint_Linux_arm64.tar.gz"
      sha256 "c0ac3bb14123fc087bb153e59938a980a022b277641ff8af6fc944e915a9e359"
    end
  end

  # No zap stanza required
end
